
logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.http=DEBUG

logging.level.com.innowise.userservice=DEBUG

logging.level.com.fasterxml.jackson.databind=DEBUG

logging.level.org.springframework.validation=DEBUG

logging.level.org.springframework.web.servlet.mvc=DEBUG

logging.level.org.springframework.cache: TRACE

logging.level.org.springframework.data.redis: DEBUG